version: "3.7"

services:

  db:
    build: ./db
    container_name: db
    env_file: .env
    expose:
      - "${POSTGRES_PORT}"
    
  app:
    build: ./app
    container_name: app
    env_file: .env
    expose:
      - "3000"
    depends_on:
      - db

  web:
    build: ./web
    container_name: web
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - app
