version: "3.7"

services:

  adminer:
    image: adminer
    container_name: ${COMPONENT_NAME_PREFIX}_adminer
    restart: always
    networks: 
      - internal-network
    expose:
      - ${ADMINER_PORT}

  db:
    build:
      context: ./db
      args:
        postgres_image: ${POSTGRES_IMAGE}
    image: ${COMPONENT_NAME_PREFIX}_db:${COMPONENT_VERSION}
    container_name: ${COMPONENT_NAME_PREFIX}_db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file: .secrets
    networks: 
      - internal-network
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      args:
        node_image: ${NODE_IMAGE}
    image: ${COMPONENT_NAME_PREFIX}_app:${COMPONENT_VERSION}
    container_name: ${COMPONENT_NAME_PREFIX}_app
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - APP_PORT=${APP_PORT}
    env_file: .secrets
    networks: 
      - internal-network
    expose:
      - "${APP_PORT}"
    depends_on:
      - db

  web:
    build:
      context: ./web
      args:
        nginx_image: ${NGINX_IMAGE}
    image: ${COMPONENT_NAME_PREFIX}_web:${COMPONENT_VERSION}
    container_name: ${COMPONENT_NAME_PREFIX}_web
    environment:
      - WEB_PORT=${WEB_PORT}
      - ADMINER_HOST=${ADMINER_HOST}
      - ADMINER_PORT=${ADMINER_PORT}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    networks:
      - internal-network
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - app

volumes:
  db_data:
    name: ${COMPONENT_NAME_PREFIX}_db_data

networks: 
  internal-network:
    name: ${COMPONENT_NAME_PREFIX}_network
