version: "3.7"

services:

  db:
    build:
      context: ./db
      args:
        postgres_image: ${POSTGRES_IMAGE}
    image: ${COMPONENT_NAME_PREFIX}_db:${COMPONENT_VERSION}
    container_name: ${COMPONENT_NAME_PREFIX}_db
    env_file: .env
    networks: 
      - internal-network
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      args:
        node_image: ${NODE_IMAGE}
    image: ${COMPONENT_NAME_PREFIX}_app:${COMPONENT_VERSION}
    container_name: ${COMPONENT_NAME_PREFIX}_app
    env_file: .env
    networks: 
      - internal-network
    expose:
      - "${APP_PORT}"
    depends_on:
      - db

  web:
    build:
      context: ./web
      args:
        nginx_image: ${NGINX_IMAGE}
    image: ${COMPONENT_NAME_PREFIX}_web:${COMPONENT_VERSION}
    container_name: ${COMPONENT_NAME_PREFIX}_web
    env_file: .env
    networks: 
      - internal-network
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - app

volumes:
  db_data:
    name: ${COMPONENT_NAME_PREFIX}_db_data

networks: 
  internal-network:
    name: ${COMPONENT_NAME_PREFIX}_network